# CAT I
- name: "HIGH | V-38666 | AUDIT | The system must use and update a DoD-approved virus scan program"
  command: /etc/init.d/nails status
  ignore_errors: yes
  check_mode: no
  changed_when: no
  register: av_nails_status_audit
  tags:
      - cat1
      - high
      - V-38666
      - antivirus
      - audit

- name: "HIGH | V-38666 | AUDIT | The system must use and update a DoD-approved virus scan program"
  shell: grep uvscan /etc/cron* /var/spool/cron/*
  register: av_uvscan_cron_audit
  ignore_errors: yes
  check_mode: no
  changed_when: no
  tags:
      - cat1
      - V-38666
      - antivirus
      - audit
      - high

- name: "HIGH | V-38666 | AUDIT | The system must use and update a DoD-approved virus scan program. Looking for virus definitions older than seven days."
  command: find /usr/local/uvscan -type f -mtime +7
  register: av_defs_audit
  changed_when: no
  ignore_errors: yes
  check_mode: no
  tags:
      - cat1
      - V-38666
      - antivirus
      - high
      - audit

- name: "HIGH | V-38677 | AUDIT | The NFS server must not have the insecure file locking option enabled"
  command: grep insecure_locks /etc/exports
  register: nfs_insecure_locking_audit
  ignore_errors: yes
  changed_when: no
  check_mode: no
  tags:
      - cat1
      - high
      - V-38677
      - audit
      - nfs

# CAT II
- name: "MEDIUM | V-38499 | AUDIT | The /etc/passwd file must not contain password hashes"
  shell: "awk -F: '($2 != \"x\") {print}' /etc/passwd"
  changed_when: false
  check_mode: no
  register: etc_password_hash_audit
  tags:
      - cat2
      - V-38499
      - medium
      - passwords
      - audit

- name: "MEDIUM | V-38500 | AUDIT | The root account must be the only account having a UID of 0"
  shell: "awk -F: '($3 == \"0\") {print}' /etc/passwd | grep -v root"
  changed_when: no
  check_mode: no
  ignore_errors: yes
  register: users_uid_0_audit
  tags:
      - cat2
      - medium
      - V-38500
      - accounts
      - audit

- name: "MEDIUM | V-38520 | AUDIT | The operating system must back up audit records on an organization defined frequency onto a different system or media than the system being audited.\n
         MEDIUM | V-38521 | AUDIT | The operating system must support the requirement to centrally manage the content of audit records generated by organization defined information system components."
  shell: grep -E '^\*\.\*\s*[@:]{1,2}[a-z.:]*' /etc/rsyslog.conf
  changed_when: no
  ignore_errors: yes
  check_mode: no
  register: rsyslog_log_mgmt_audit
  tags:
      - audit
      - V-38520
      - V-38521
      - rsyslog
      - logging
      - cat2
      - medium

- name: "MEDIUM | V-38625 | AUDIT | If the system is using LDAP for authentication or account information the system must use a TLS connection using FIPS 140-2 approved cryptographic algorithms"
  shell: ps -ef | grep [s]lapd
  register: ldap_tls_audit
  when: "'slapd' in sysv_services.stdout"
  ignore_errors: yes
  changed_when: no
  tags:
      - cat2
      - medium
      - audit
      - V-38625
      - ldap

- name: "MEDIUM | V-38643 | AUDIT | There must be no world-writable files on the system."
  command: find / -xdev -type f -perm -002
  register: world_writable_files
  changed_when: false
  tags:
      - cat2
      - medium
      - audit
      - V-38643
      - file_perms

- name: "MEDIUM | V-38652 | AUDIT | Remote file systems must be mounted with the 'nodev' option"
  shell: mount | grep 'type nfs' | grep -v 'nodev'
  changed_when: false
  register: nfs_mounts_missing_nodev
  failed_when: nfs_mounts_missing_nodev.stderr
  tags:
      - cat2
      - medium
      - audit
      - V-38652
      - nfs

- name: "MEDIUM | V-38654 | PATCH | Remote file systems must be mounted with the nosuid option"
  shell: mount | grep 'type nfs' | grep -v 'nosuid'
  changed_when: false
  failed_when: nfs_mounts_missing_nosuid.stderr
  register: nfs_mounts_missing_nosuid
  tags:
      - cat2
      - medium
      - audit
      - V-38654
      - nfs

- name: "MEDIUM | V-38660 | AUDIT | The snmpd service must use only SNMP protocol version 3 or newer."
  shell: "grep -E 'v1|v2c|com2sec' /etc/snmp/snmpd.conf | grep -v '^#'"
  changed_when: false
  register: snmp_version_check
  failed_when: '"FAIL" in snmp_version_check.stdout'
  when: snmpconf_test.stat.exists
  tags:
      - cat2
      - medium
      - audit
      - V-38660
      - snmp

# CAT III
- name: "LOW | V-38455 | AUDIT | The system must use a separate file system for /tmp"
  shell: mount | grep "on /tmp "
  register: tmp_mounted_audit
  check_mode: no
  ignore_errors: yes
  changed_when: no
  tags:
      - cat3
      - low
      - V-38455
      - partitions
      - audit

- name: "LOW | V-38456 | AUDIT | The system must use a separate file system for /var"
  shell: mount | grep "on /var "
  register: var_mounted_audit
  changed_when: no
  ignore_errors: yes
  check_mode: no
  tags:
      - cat3
      - V-38456
      - partitions
      - low
      - audit

- name: "LOW | V-38463 | AUDIT | The system must use a separate file system for /var/log"
  shell: mount | grep "on /var/log "
  register: varlog_mounted_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - high
      - V-38463
      - partitions
      - audit

- name: "LOW | V-38467 | AUDIT | The system must use a separate file system for /var/log/audit"
  shell: mount | grep "on /var/log/audit "
  register: varlogaudit_mounted_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - V-38467
      - partitions
      - audit

- name: "LOW | V-38473 | AUDIT | The system must use a separate file system for user home directories"
  shell: mount | grep "on /home "
  register: home_mounted_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags:
      - cat3
      - low
      - V-38473
      - partitions
      - audit

- name: "LOW | V-38681 | AUDIT | All GIDs referenced in /etc/passwd must be defined in /etc/group"
  shell: pwck -r | grep 'no group'
  changed_when: false
  failed_when: false
  register: missing_group_audit
  check_mode: no
  tags:
      - cat3
      - low
      - V-38681
      - accounts
      - audit

- name: "LOW | V-38683 | AUDIT | All accounts on the system must have unique user or account names"
  shell: pwck -rq | grep -A1 'duplicate' | grep -v 'duplicate'
  changed_when: false
  failed_when: false
  register: duplicate_account_audit
  check_mode: no
  tags:
      - cat3
      - low
      - V-38683
      - accounts
      - audit

- name: " LOW | V-38697 | AUDIT | The sticky bit must be set on all public directories."
  shell: "lsblk | awk '$6 == \"part\" && $7 ~ /\\// {print $NF}' | xargs -I{} find {} -xdev -type d -perm -0002 \\! -perm -1000"
  changed_when: false
  register: stick_bit_public_dir_audit
  check_mode: no
  tags:
      - cat3
      - low
      - V-38697
      - permissions
      - sticky_bit
      - audit

- name: " LOW | V-38699 | AUDIT | All public directories must be owned by a system account."
  shell: "lsblk | awk '$6 == \"part\" && $7 ~ /\\// {print $NF}' | xargs -I{} find {} -xdev -type d -perm -0002 -uid +499 -print"
  changed_when: false
  register: system_account_public_dir_audit
  check_mode: no
  tags:
      - cat3
      - low
      - V-38699
      - permissions
      - public_dir_ownership
      - audit
