---
# tasks register to satellite6 with or without puppet
#
- name: Download bootstrap.py from the {{ satellite_hostname }}
  get_url:
    url: "http://{{ satellite_hostname }}/pub/bootstrap.py"
    dest: /usr/local/sbin/bootstrap.py
  when: hostgroup != 'false'
  register: get_url_result
  until: get_url_result | succeeded
  retries: 10
  delay: 1
  ignore_errors: yes

- name: Copy bootstrap.py script to /usr/local/sbin and make it executable
  file:
    path: /usr/local/sbin/bootstrap.py
    mode: 0755
    owner: root
    group: root
  when: hostgroup != 'false'

- name: Register to Satellite6 with puppet enabled and add it to the correct hostgroup
  command: "/usr/local/sbin/bootstrap.py -l {{ satellite_user}} -p {{ satellite_pass }} -s {{ satellite_hostname }} -o '{{ organization }}' -L '{{ location }}' -g {{ hostgroup }} -a {{ activation_key }} -f"
  when: hostgroup != 'false'

- name: Set Up satellite Repo
  shell: "{{ item }}"
  register: sat_repos_output
  with_items:
    - subscription-manager repos --enable rhel-7-server-satellite-tools-6.3-rpms

- name: Log sat_repos_output
  debug:
    var: sat_repos_output
  when: verbose and sat_repos_output is defined

- name: Install the katello-ca-consumer-latest.noarch.rpm from {{ satellite_hostname }}
  yum:
    name: http://{{ satellite_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
  when: hostgroup == 'false'

- name: Register to Satellite6 only for content
  redhat_subscription:
    state: present
    activationkey: "{{ activation_key }}"
    org_id: "{{ organization }}"
    autosubscribe: true
  when: hostgroup == 'false'
  register: 'reg_return'

- name: Install the katello-agent
  yum:
    name: katello-agent
    state: latest
  when: hostgroup == 'false' and reg_return|success
  notify:
    - Start katello-agent
    - Enable katello-agent

- name: Update the host to latest errata within the attached content view
  yum:
    name: '*'
    state: latest
  when: updatehost != 'false'
