---
- block:
  - name: Login to oVirt engine
    ovirt_auth:
      username: "{{ engine_user | default(omit) }}"
      password: "{{ engine_password | default(omit) }}"
      url: "{{ engine_url | default(omit) }}"
      ca_file: "{{ engine_cafile | default(omit) }}"
      insecure: "{{ engine_cafile is undefined }}"

  - block:
    - name: Provision instances asynchronously
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: running
        name: "{{ item }}"
        cluster: "{{ cluster }}"
        template: "{{ template }}"
        memory: "{{ memory_mb | default(omit) }}"
        cpu_cores: "{{ cpu_cores | default(omit) }}"
        cpu_sockets: "{{ cpu_sockets | default(omit) }}"
        operating_system: "{{ operating_system | default(omit) }}"
        comment: "{{ comment | default(omit) }}"
        description: "{{ description | default(omit) }}"
        type: "{{ type | default('server') }}"
        disks: "{{ disks | default(omit) }}"
        nics: "{{ networks | default(omit) }}"
        cloud_init:
          host_name: "{{ item }}.{{ dns_suffix }}"
          custom_script: "{{ custom_script }}"
      with_items: "{{ vm_names }}"
      register: rhv_created_vms_async
      async: "{{ async_wait }}"
      poll: "{{ async_poll }}"

    - name: Wait for asynchronous job to complete
      async_status: jid={{ item.ansible_job_id }}
      register: rhv_created_vms
      until: rhv_created_vms.finished
      retries: "{{ async_retries }}"
      with_items: "{{ rhv_created_vms_async.results }}"

    - name: Log rhv_created_vms
      debug:
        var: rhv_created_vms
      when: verbose

    - name: Wait for VM IP
      ovirt_vms_facts:
        auth: "{{ ovirt_auth }}"
        pattern: "id={{ item.id }}"
        fetch_nested: true
        nested_attributes: ips
      until: ovirt_vms | first | json_query('reported_devices[0].ips[0].address') | ipv4
      with_items: "{{ rhv_created_vms.results }}"
      retries: "{{ wait_for_ip_retries }}"
      delay: "{{ wait_for_ip_delay }}"
      register: wait_for_ip_output
      when: wait_for_ip_address

    - name: Log wait_for_ip_output
      debug:
        msg: "{{ item.ansible_facts.ovirt_vms[0]|json_query('reported_devices[0].ips[0].address')|ipv4 }}"
      with_items: "{{ wait_for_ip_output.results }}"
      when: wait_for_ip_address and verbose

    - name: "Add new vm ip addresses to rhv_hosts group"
      add_host:
        name: "{{ item.ansible_facts.ovirt_vms[0]|json_query('reported_devices[0].ips[0].address')|ipv4 }}"
        groups: rhv_hosts
      with_items: "{{ wait_for_ip_output.results }}"
      when: wait_for_ip_address

  rescue:
    - name: Remove VM if deploy fails
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        name: "{{ item }}"
        state: absent
      with_items: "{{ vm_names }}"
      when: remove_vms_on_error

  always:
    - name: Logout from oVirt engine
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
