---
galaxy_info:
  author: "Dan Shepherd, Jon Davila, Sam Doran"
  description: "Ansible role to apply RHEL 6 STIG"
  company: "MindPoint Group"
  license: MIT
  min_ansible_version: 2.1
  version: 1.0

  platforms:
  - name: EL
    versions:
      - 6
  - name: CentOS
    versions:
      - 6

  galaxy_tags:
    - system
    - security
    - stig
    - hardening

dependencies: []
