---
# defaults file for rhel7-role-pci-dss

account_disable_post_pw_expiration: true
accounts_maximum_age_login_defs: true
accounts_password_pam_dcredit: true
accounts_password_pam_lcredit: true
accounts_password_pam_minlen: true
accounts_password_pam_ucredit: true
accounts_password_pam_unix_remember: true
accounts_passwords_pam_faillock_deny: true
accounts_passwords_pam_faillock_unlock_time: true
aide_build_database: true
aide_periodic_cron_checking: true
audit_rules_dac_modification_chmod: true
audit_rules_dac_modification_chown: true
audit_rules_dac_modification_fchmod: true
audit_rules_dac_modification_fchmodat: true
audit_rules_dac_modification_fchown: true
audit_rules_dac_modification_fchownat: true
audit_rules_dac_modification_fremovexattr: true
audit_rules_dac_modification_fsetxattr: true
audit_rules_dac_modification_lchown: true
audit_rules_dac_modification_lremovexattr: true
audit_rules_dac_modification_lsetxattr: true
audit_rules_dac_modification_removexattr: true
audit_rules_dac_modification_setxattr: true
audit_rules_privileged_commands: true
auditd_data_retention_action_mail_acct: true
auditd_data_retention_admin_space_left_action: true
auditd_data_retention_max_log_file: true
auditd_data_retention_max_log_file_action: true
auditd_data_retention_num_logs: true
auditd_data_retention_space_left_action: true
configure_strategy: true
dconf_gnome_screensaver_idle_activation_enabled: true
dconf_gnome_screensaver_idle_delay: true
dconf_gnome_screensaver_lock_enabled: true
dconf_gnome_screensaver_mode_blank: true
dconf_use_text_backend: true
disable_prelink: true
enable_strategy: true
ensure_gpgcheck_globally_activated: true
ensure_gpgcheck_never_disabled: true
ensure_redhat_gpgkey_installed: true
file_groupowner_etc_group: true
file_groupowner_etc_passwd: true
file_groupowner_etc_shadow: true
file_groupowner_grub2_cfg: true
file_owner_etc_group: true
file_owner_etc_passwd: true
file_owner_etc_shadow: true
file_owner_grub2_cfg: true
file_permissions_etc_group: true
file_permissions_etc_passwd: true
file_permissions_etc_shadow: true
high_complexity: true
high_disruption: true
high_severity: true
low_complexity: true
low_disruption: true
medium_complexity: true
medium_disruption: true
medium_severity: true
no_empty_passwords: true
package_aide_installed: true
package_libreswan_installed: true
patch_strategy: true
restrict_strategy: true
rpm_verify_hashes: true
rpm_verify_permissions: true
security_patches_up_to_date: true
service_auditd_enabled: true
set_password_hashing_algorithm_libuserconf: true
set_password_hashing_algorithm_logindefs: true
skip_ansible_lint: true
sshd_set_idle_timeout: true
unknown_strategy: true
