---
galaxy_info:
  author: ramrexx
  description: rhv_vmname
  company:
  license: Apache
  issue_tracker_url:
  github_branch:
  min_ansible_version: 2.4
  platforms:
    name: EL
    versions:
      - 7
  categories:
    - manageiq
    - cloudforms
dependencies: []
