---
# For a full list of ovirt_vms parameters, visit:
# http://docs.ansible.com/ansible/latest/ovirt_vms_module.html

# RHV Auth parameters
# engine_url: "{{ lookup('env', 'OVIRT_URL') }}"
# engine_user: "{{ lookup('env', 'OVIRT_USERNAME') }}"
# engine_password: "{{ lookup('env', 'OVIRT_PASSWORD') }}"
# engine_cafile: "{{ lookup('env', 'OVIRT_CAFILE') }}"

engine_url: "{{ lookup('env', 'OVIRT_URL') }}"
engine_user: "{{ lookup('env', 'OVIRT_USERNAME') }}"
engine_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32343765326564333435653736376236303139666364343432313831326337386433356361373361
          3830633930373435366632343039353239326132376537630a653031636261353663353336373665
          33346534656134343765353434646237666164393766353364626266353332323239623565343063
          6432363234323161390a323061633334653137363162373032326338666639613239623664353030
          3863

template:
cluster: Default

# vm guest parameters
vm_names:
  - vm_name:
memory: 1GiB
cpu_cores: 1
cpu_sockets: 1
operating_system: rhel_7x64
type: server
description:
comment: Provisioned via Ansible
state: poweredon
wait_for_ip_address: true
remove_vms_on_error: true

## vm networking parameters
nics:
  - name: "{{ network_0_name | default('nic1') }}"
    profile_name: "{{ network_0_vlan | default('ovirtmgmt') }}"
    ### interface - (virtio, e1000, rtl8139)
    # interface: "{{ network_0_interface | default('virtio') }}"

## vm disk parameters
# disks:
#   - name: "{{ disk_0_name | default('disk1') }}"
#     bootable: "{{ disk_0_bootable | default(true) }}"

dns_suffix: .example.com

# cloud_init script
custom_script: |
  disable_root: false
  users:
    - name: root
      lock_passwd: false
      ssh_authorized_keys:
        - "{{ ssh_authorized_key | default(omit) }}"
  runcmd:
    - "touch /etc/cloud/cloud-init.disabled"
    - systemctl stop firewalld
    - systemctl disable firewalld
# asynchronous parameters
async_wait: 3600
async_poll: 0
async_retries: 100

# setup retry variables
wait_for_ip_retries: 30
wait_for_ip_delay: 10

# enable extra debugging
verbose: false
