galaxy_info:
  author: Thomas Woerner <twoerner@redhat.com>
  description: Configure firewalld and system-config-firewall/lokkit
  company: Red Hat, Inc.
  license: GPLv2+
  min_ansible_version: 2.2
  galaxy_tags: [ 'firewall', 'system', 'beta' ]
  platforms:
    - name: Fedora
      versions: [ 24, 25 ]
    - name: EL
      versions: [ 6, 7 ]
