---
- name: "Checking to see if httpd is installed prior to us installing it"
  stat:
    path: "/usr/lib/systemd/system/httpd.service"
  register: wassvchttpd

- name: installing the required software
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - unzip
    - MySQL-python
#    - mysql-connector-python
    - policycoreutils-python
    - httpd
    - php
    - php-mysql
    - mariadb
#    - libselinux-python
