---
- name: Deploy WordPress to lampweb and lampdb
  hosts: all

  vars:
    - webhostname: "{{ hostvars['lampweb']['ansible_nodename'] }}"
    - dbhostname: "{{ hostvars['lampdb']['ansible_facts']['eth0']['ipv4']['address'] }}"


  roles:
    - role: force-reg
    - role: wordpress-server
