---
- name: restart ntpd
  service: name=ntpd state=restarted

- name: restart ssh
  service: name=sshd state=restarted

- name: restart snmpd
  service: name=snmpd state=restarted

- name: restart xinetd
  service: name=xinetd state=restarted

- name: reload xinetd
  service: name=xinetd state=reloaded

- name: restart auditd
  service: name=auditd state=restarted

- name: unload usb-storage
  modprobe: name=usb-storage state=absent

- name: update postfix aliases.db
  command: newaliases

- name: restart postfix
  service: name=postfix state=restarted

- name: restart gdm
  shell: telinit 3; sleep 2; telinit 5

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: restart vsftpd
  service: name=vsftpd state=restarted

- name: restart samba
  service: name=smb state=restarted
  when: "'smb' in sysv_services.stdout"

- name: restart nfs
  service: name=nfs state=restarted

- name: init aide
  command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
  async: 45
  poll: 0

- name: reset audit pkg perms
  command: rpm --setperms audit

- name: reset audit pkg ugids
  command: rpm --setugids audit
