---
satellite_user: admin
satellite_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32343765326564333435653736376236303139666364343432313831326337386433356361373361
          3830633930373435366632343039353239326132376537630a653031636261353663353336373665
          33346534656134343765353434646237666164393766353364626266353332323239623565343063
          6432363234323161390a323061633334653137363162373032326338666639613239623664353030
          3863
satellite_hostname: sat6.summit.example.com
validate_certs: false
force_basic_auth: true
policy_id:
vm_hostname:
verbose: false
